### ISSUE TITLE
Don't Replace Classes

### ISSUE THREAD

**Issue by lynnwallenstein** [bruce/goose#3]
Code:

https://gist.github.com/9650b452fe68cf6e900d

Renders: 

https://gist.github.com/3a2a8a14ef6a8c7a54f4

Which is good... but when you nav_at Coding Styles:

https://gist.github.com/83aa3cf8a503c21e11da

The problem is that the active state, which in the goose.rb is "is-active" replaced the "dropdown" state.... I need it to add is-active, not replace.

**Comment by bruce** [comment]
Please check latest HEAD

**Comment by bruce** [comment]
This should be handled by 864715c920d557f4f6212b782d80355fb10c90b6 (& verified in subsequent test)
